### ISSUE TITLE
Debian Bug#967538: ipwatchd-gnotify: depends on deprecated GTK 2

### ISSUE THREAD

**Issue by jariq** [jariq/IPwatchD#13]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967538

**Comment by bgermann** [comment]
Is ipwatchd-gnotify supposed to be part of this project? It was separate on sourceforge and is not contained here.

**Comment by jariq** [comment]
`ipwatchd-gnotify` was depecated in [IPwatchD 1.3](https://github.com/jariq/IPwatchD/releases/tag/v1.3.0) 5 years ago and I don't plan to resurrect or maintain it anymore.

**Comment by jariq** [comment]
`ipwatchd-gnotify` was [removed from debian](https://bugs.debian.org/1049368).
