### ISSUE TITLE
Missing ipwatchd config file

### ISSUE THREAD

**Issue by simmonsm** [jariq/IPwatchD#19]
Just pulled down a copy using git and did a build and build install.
The file /usr/local/etc/ipwatchd.conf is missing on my Linux:
```
sudo make install
mkdir -p /etc
mkdir -p /lib/systemd/system
mkdir -p /usr/sbin
mkdir -p /usr/share/man/man8
mkdir -p /usr/share/man/man5
mkdir -p /usr/share/man/man1
cp ipwatchd /usr/sbin
cp ipwatchd-script /usr/sbin
cp ipwatchd.service /lib/systemd/system
cp ipwatchd.conf /etc
cp ../doc/ipwatchd.8.gz /usr/share/man/man8
cp ../doc/ipwatchd.conf.5.gz /usr/share/man/man5
cp ../doc/ipwatchd-script.1.gz /usr/share/man/man1
```
System:    Kernel: 5.4.0-84-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by jariq** [comment]
It's in `/etc/ipwatchd.conf`.

**Comment by simmonsm** [comment]
thanks
